# Generated by Django 6.0.2 on 2026-02-12 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('вік', models.FloatField(blank=True, null=True)),
                ('зріст', models.FloatField(blank=True, null=True)),
                ('вага', models.FloatField(blank=True, null=True)),
                ('обхват_талії', models.FloatField(blank=True, null=True)),
                ('емоційний_стрес', models.FloatField(blank=True, null=True)),
                ('алкоголь', models.FloatField(blank=True, null=True)),
                ('калораж', models.FloatField(blank=True, null=True)),
                ('віджимання_max', models.FloatField(blank=True, null=True)),
                ('підтягування_max', models.FloatField(blank=True, null=True)),
                ('біг_1км', models.FloatField(blank=True, null=True)),
                ('біг_100м', models.FloatField(blank=True, null=True)),
                ('тест_купера', models.FloatField(blank=True, null=True)),
                ('бурпі_3хв', models.FloatField(blank=True, null=True)),
                ('віджимання_1хв', models.FloatField(blank=True, null=True)),
                ('сон', models.FloatField(blank=True, null=True)),
                ('пульс_спокою', models.FloatField(blank=True, null=True)),
                ('тиск_верхній', models.FloatField(blank=True, null=True)),
                ('мітохондрії', models.FloatField(blank=True, null=True)),
                ('тестостерон', models.FloatField(blank=True, null=True)),
                ('кортизол', models.FloatField(blank=True, null=True)),
                ('гемоглобін', models.FloatField(blank=True, null=True)),
                ('срб', models.FloatField(blank=True, null=True)),
                ('прогноз', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('план', models.JSONField()),
                ('створено', models.DateTimeField(auto_now_add=True)),
                ('user_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.userinput')),
            ],
        ),
        migrations.AddField(
            model_name='userinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='fitness.userprofile'),
        ),
    ]
