# Generated by Django 6.0.2 on 2026-02-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('вік', models.FloatField(blank=True, null=True)),
                ('зріст', models.FloatField(blank=True, null=True)),
                ('вага', models.FloatField(blank=True, null=True)),
                ('обхват_талії', models.FloatField(blank=True, null=True)),
                ('емоційний_стрес', models.FloatField(blank=True, null=True)),
                ('алкоголь', models.FloatField(blank=True, null=True)),
                ('калораж', models.FloatField(blank=True, null=True)),
                ('віджимання_max', models.FloatField(blank=True, null=True)),
                ('підтягування_max', models.FloatField(blank=True, null=True)),
                ('біг_1км', models.FloatField(blank=True, null=True)),
                ('біг_100м', models.FloatField(blank=True, null=True)),
                ('тест_купера', models.FloatField(blank=True, null=True)),
                ('бурпі_3хв', models.FloatField(blank=True, null=True)),
                ('віджимання_1хв', models.FloatField(blank=True, null=True)),
                ('сон', models.FloatField(blank=True, null=True)),
                ('пульс_спокою', models.FloatField(blank=True, null=True)),
                ('тиск_верхній', models.FloatField(blank=True, null=True)),
                ('мітохондрії', models.FloatField(blank=True, null=True)),
                ('тестостерон', models.FloatField(blank=True, null=True)),
                ('кортизол', models.FloatField(blank=True, null=True)),
                ('гемоглобін', models.FloatField(blank=True, null=True)),
                ('срб', models.FloatField(blank=True, null=True)),
                ('прогноз', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainingplan',
            name='user_input',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='user_data',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.userdata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.usersession'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserInput',
        ),
    ]
